# Arquivo: ./docker-compose.yml
version: '3.8'

networks:
  monitoring:
    driver: bridge

services:
  # === Backend (API Node/Express + Prisma) ===
  backend:
    build:
      context: ./backend
    container_name: zenit-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.docker   # variáveis de runtime do app
    depends_on:
      - db
    networks:
      - monitoring

  # === Banco de Dados Postgres ===
  db:
    image: postgres:14-alpine
    container_name: zenit-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=zenit
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/docker/initdb:/docker-entrypoint-initdb.d
    networks:
      - monitoring

  # === Prometheus ===
  prometheus:
    image: prom/prometheus:latest
    container_name: zenit-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend
    networks:
      - monitoring

  # === Grafana ===
  grafana:
    image: grafana/grafana:latest
    container_name: zenit-grafana
    ports:
      - '3030:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring
  
    # === pgAdmin ===
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zenit-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - monitoring

  # === Frontend Next.js ===
  frontend:
    build:
      context: ./frontend
    container_name: zenit-frontend
    ports:
      - '3001:3000'
    env_file:
      - ./frontend/.env.local   # NEXT_PUBLIC_API_URL etc.
    depends_on:
      - backend
    networks:
      - monitoring

volumes:
  postgres-data:
  pgadmin-data: