# docker-compose.yml - REDIS DESABILITADO
version: '3.8'

services:
  # === Banco de Dados Postgres (DEVE SUBIR PRIMEIRO) ===
  db:
    image: postgres:14-alpine
    container_name: zenit-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zenit
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/docker/initdb:/docker-entrypoint-initdb.d
    networks:
      - monitoring
    # ✅ CRÍTICO: Health check real do PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zenit"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # === pgAdmin ===
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zenit-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - monitoring

volumes:
  postgres-data:
  pgadmin-data: